# Generated by Django 5.1.3 on 2025-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
